/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package millionairegame;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Random;
import static millionairegame.QuestionPool.answer;

/**
 *
 * @author gandharparanjape
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        startPage.setVisible(true);
        rulesPage.setVisible(false);
        questionPage.setVisible(false);
        sidePanel.setVisible(false);
        gamelostFrame.setVisible(false);
        confirmAnswer.setEnabled(false);
        pafFrame.setVisible(false);
        fiftyfiftyFrame.setVisible(false);
        ataFrame.setVisible(false);
        gamewonFrame.setVisible(false);
        incorrectnameFrame.setVisible(false);
        plcount = 0;
        $0.setBackground(Color.RED);
        String a = "a";
        String b = "b";
        String c = "c";
        String d = "d";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        sidePanel = new javax.swing.JPanel();
        $0 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        $500 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        $1000 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        $2000 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        $3000 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        $5000 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        $7500 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        $10000 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        $15000 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        $25000 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        $50000 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        $75000 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        $250000 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        $500000 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        $1000000 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        nameButton = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        questionPage = new javax.swing.JPanel();
        gamewonFrame = new javax.swing.JInternalFrame();
        gamewonLabel = new javax.swing.JLabel();
        closegameButton1 = new javax.swing.JButton();
        Question = new javax.swing.JLabel();
        insertquestion = new javax.swing.JLabel();
        confirmAnswer = new javax.swing.JButton();
        pafButton = new javax.swing.JToggleButton();
        ataButton = new javax.swing.JToggleButton();
        fiftyfiftyButton = new javax.swing.JToggleButton();
        ataFrame = new javax.swing.JInternalFrame();
        ataLabel = new javax.swing.JLabel();
        closeButton2 = new javax.swing.JButton();
        fiftyfiftyFrame = new javax.swing.JInternalFrame();
        fiftyfiftyLabel = new javax.swing.JLabel();
        closeButton1 = new javax.swing.JButton();
        pafFrame = new javax.swing.JInternalFrame();
        closeButton = new javax.swing.JButton();
        pafLabel = new javax.swing.JLabel();
        gamelostFrame = new javax.swing.JInternalFrame();
        gamelostLabel = new javax.swing.JLabel();
        closegameButton = new javax.swing.JButton();
        optionA = new javax.swing.JToggleButton();
        optionB = new javax.swing.JToggleButton();
        optionC = new javax.swing.JToggleButton();
        optionD = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        closegameButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        rulesPage = new javax.swing.JPanel();
        ButtonPlay = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        startPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonNG = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nametextfield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        incorrectnameFrame = new javax.swing.JInternalFrame();
        gamelostLabel1 = new javax.swing.JLabel();
        closegameButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 0, 0));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        $0.setBackground(new java.awt.Color(51, 102, 255));
        $0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$0");
        $0.add(jLabel3);

        sidePanel.add($0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 475, 180, 30));

        $500.setBackground(new java.awt.Color(51, 102, 255));
        $500.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$500\n");
        $500.add(jLabel4);

        sidePanel.add($500, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 180, 30));

        $1000.setBackground(new java.awt.Color(51, 102, 255));
        $1000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("$1000");
        $1000.add(jLabel5);

        sidePanel.add($1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 415, 180, 30));

        $2000.setBackground(new java.awt.Color(51, 102, 255));
        $2000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("$2000");
        $2000.add(jLabel6);

        sidePanel.add($2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 180, 30));

        $3000.setBackground(new java.awt.Color(51, 102, 255));
        $3000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("$3000\n");
        $3000.add(jLabel7);

        sidePanel.add($3000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, 180, 30));

        $5000.setBackground(new java.awt.Color(51, 102, 255));
        $5000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("$5000");
        $5000.add(jLabel8);

        sidePanel.add($5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, 180, 30));

        $7500.setBackground(new java.awt.Color(51, 102, 255));
        $7500.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$7500\n");
        $7500.add(jLabel9);

        sidePanel.add($7500, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 295, 180, 30));

        $10000.setBackground(new java.awt.Color(51, 102, 255));
        $10000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("$10,000");
        $10000.add(jLabel10);

        sidePanel.add($10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 180, 30));

        $15000.setBackground(new java.awt.Color(51, 102, 255));
        $15000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("$15,000\n");
        $15000.add(jLabel11);

        sidePanel.add($15000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 235, 180, 30));

        $25000.setBackground(new java.awt.Color(51, 102, 255));
        $25000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$25,000\n");
        $25000.add(jLabel12);

        sidePanel.add($25000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 180, 30));

        $50000.setBackground(new java.awt.Color(51, 102, 255));
        $50000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        $50000.setForeground(new java.awt.Color(255, 255, 51));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("$50,000\n");
        $50000.add(jLabel13);

        sidePanel.add($50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 180, 30));

        $75000.setBackground(new java.awt.Color(51, 102, 255));
        $75000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("$75,000\n");
        $75000.add(jLabel14);

        sidePanel.add($75000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 145, 180, 30));

        $250000.setBackground(new java.awt.Color(51, 102, 255));
        $250000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("$250,000");
        $250000.add(jLabel15);

        sidePanel.add($250000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 180, 30));

        $500000.setBackground(new java.awt.Color(51, 102, 255));
        $500000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("$500,000");
        $500000.add(jLabel16);

        sidePanel.add($500000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 180, 30));

        $1000000.setBackground(new java.awt.Color(51, 102, 255));
        $1000000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setText("$1,000,000");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setAlignmentY(0.0F);
        $1000000.add(jLabel17);

        sidePanel.add($1000000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 180, 40));

        nameButton.setBackground(new java.awt.Color(51, 102, 255));
        nameButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameButton.add(nameLabel);

        sidePanel.add(nameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 180, 500));

        questionPage.setBackground(new java.awt.Color(0, 0, 0));
        questionPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamewonFrame.setVisible(true);
        gamewonFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamewonLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        gamewonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamewonLabel.setText("<html>CONGRATULATIONS! YOU HAVE <br/>FINISHED THE GAME! YOU ARE NOW OFFICIALLY A MILLIONAIRE!<html/>");
        gamewonFrame.getContentPane().add(gamewonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 104));

        closegameButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        closegameButton1.setText("Quit Game");
        closegameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closegameButton1ActionPerformed(evt);
            }
        });
        gamewonFrame.getContentPane().add(closegameButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, 50));

        questionPage.add(gamewonFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 350, 270));

        Question.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 51));
        Question.setText("Question");
        questionPage.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 50));

        insertquestion.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        insertquestion.setForeground(new java.awt.Color(255, 255, 51));
        questionPage.add(insertquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 740, 40));

        confirmAnswer.setBackground(new java.awt.Color(255, 255, 51));
        confirmAnswer.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        confirmAnswer.setText("Confirm Answer");
        confirmAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerListener(evt);
            }
        });
        questionPage.add(confirmAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 190, 60));

        pafButton.setBackground(new java.awt.Color(0, 0, 0));
        pafButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pafButton.setForeground(new java.awt.Color(255, 255, 51));
        pafButton.setText("Phone a Friend");
        pafButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pafButtonActionPerformed(evt);
            }
        });
        questionPage.add(pafButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 60));

        ataButton.setBackground(new java.awt.Color(0, 0, 0));
        ataButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ataButton.setForeground(new java.awt.Color(255, 255, 51));
        ataButton.setText("Ask the Audience");
        ataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataButtonActionPerformed(evt);
            }
        });
        questionPage.add(ataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 220, 60));

        fiftyfiftyButton.setBackground(new java.awt.Color(0, 0, 0));
        fiftyfiftyButton.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        fiftyfiftyButton.setForeground(new java.awt.Color(255, 255, 51));
        fiftyfiftyButton.setText("5050\n");
        fiftyfiftyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyfiftyButtonActionPerformed(evt);
            }
        });
        questionPage.add(fiftyfiftyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 170, 60));

        ataFrame.setVisible(true);
        ataFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ataLabel.setText("<html>\n<br><br/>\n<br><br/>\n<br><br/>\n<br><br/>\n<html/>");
        ataFrame.getContentPane().add(ataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 104));

        closeButton2.setText("Close ");
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });
        ataFrame.getContentPane().add(closeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        questionPage.add(ataFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 500, 200));

        fiftyfiftyFrame.setVisible(true);
        fiftyfiftyFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fiftyfiftyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiftyfiftyFrame.getContentPane().add(fiftyfiftyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 104));

        closeButton1.setText("Close ");
        closeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton1ActionPerformed(evt);
            }
        });
        fiftyfiftyFrame.getContentPane().add(closeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        questionPage.add(fiftyfiftyFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 500, 200));

        pafFrame.setVisible(true);
        pafFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setText("Close ");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        pafFrame.getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        pafLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pafFrame.getContentPane().add(pafLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 450, 104));

        questionPage.add(pafFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 500, 200));

        gamelostFrame.setVisible(true);
        gamelostFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamelostLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamelostLabel.setText("<html>Your answer was wrong! You have <br/>lost the game! Thank you for playing!<html/>");
        gamelostFrame.getContentPane().add(gamelostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 104));

        closegameButton.setText("Quit Game");
        closegameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closegameButtonActionPerformed(evt);
            }
        });
        gamelostFrame.getContentPane().add(closegameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        questionPage.add(gamelostFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 600, 200));

        optionA.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup.add(optionA);
        optionA.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        optionA.setText("jToggleButton1");
        optionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAActionPerformed(evt);
            }
        });
        questionPage.add(optionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 260, 100));

        optionB.setBackground(new java.awt.Color(255, 51, 51));
        buttonGroup.add(optionB);
        optionB.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        optionB.setText("jToggleButton5");
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });
        questionPage.add(optionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 260, 100));

        optionC.setBackground(new java.awt.Color(51, 255, 51));
        buttonGroup.add(optionC);
        optionC.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        optionC.setText("jToggleButton6");
        optionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCActionPerformed(evt);
            }
        });
        questionPage.add(optionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 260, 100));

        optionD.setBackground(new java.awt.Color(255, 255, 51));
        buttonGroup.add(optionD);
        optionD.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        optionD.setText("jToggleButton7");
        optionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDActionPerformed(evt);
            }
        });
        questionPage.add(optionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 260, 100));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        questionPage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 640, 50));

        closegameButton2.setBackground(new java.awt.Color(255, 255, 51));
        closegameButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        closegameButton2.setText("Quit Game");
        closegameButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closegameButton2ActionPerformed(evt);
            }
        });
        questionPage.add(closegameButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 150, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/millionairegame/background.jpg"))); // NOI18N
        jLabel22.setText("jLabel21");
        questionPage.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, -1, -1));

        getContentPane().add(questionPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        rulesPage.setBackground(new java.awt.Color(0, 0, 0));
        rulesPage.setForeground(new java.awt.Color(255, 255, 255));
        rulesPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPlay.setBackground(new java.awt.Color(255, 255, 51));
        ButtonPlay.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        ButtonPlay.setText("PLAY");
        ButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlayActionPerformed(evt);
            }
        });
        rulesPage.add(ButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 140, 40));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("RULES");
        rulesPage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("<html><br/> 1. Simply choose one of the four options that matches the correct answer.<br/> \n2. If you get the answer correct your prize will increase.<br/> \n3. If you answer a question incorrectly you will lose the game.<br/> \n4. You have 3 lifelines that will help you in answering questions. However you <br/> \n&emsp;&emsp;can only use each lifeline once.<br/> \n5. Your 3 lifelines include:<br/> <br/> \n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;a) Ask the Audience, a percentage of the <br/>\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;audience choosing each specific option will be displayed.<br/> \n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;b) Phone a friend, your friend will give you <br/>\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;the answer they think is correct.<br/>  \n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;c) 5050, 2 incorrect options will be deleted, <br/>\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;revealing one correct and one incorrect option.<br/> <br/> \n6. There are checkpoints at $5,000 and $50,000, if your score surpasses each checkpoint, <br/>\n&emsp;&emsp;you will recieve the prize of each checkpoint. <br/> \n7. You can quit, by pressing QUIT at any stage to take the prize you are currently sitting on. </html>");
        rulesPage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rulesPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 650, 350));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/millionairegame/background.jpg"))); // NOI18N
        jLabel23.setText("jLabel21");
        rulesPage.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, -1, -1));

        getContentPane().add(rulesPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        startPage.setBackground(new java.awt.Color(0, 0, 0));
        startPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("<html>WHO WANTS TO BE A<br/> &emsp;&emsp;&emsp;MILLIONAIRE<html>");
        startPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 110));

        ButtonNG.setBackground(new java.awt.Color(255, 255, 51));
        ButtonNG.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ButtonNG.setText("NEW GAME");
        ButtonNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNGActionPerformed(evt);
            }
        });
        startPage.add(ButtonNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 140, 70));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("ENTER YOUR NAME ");
        startPage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        nametextfield.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextfieldActionPerformed(evt);
            }
        });
        startPage.add(nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 210, 50));

        jLabel20.setFont(new java.awt.Font("Brush Script MT", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 153));
        jLabel20.setText("By Gandhar Paranjape & Oliver Soons");
        startPage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        incorrectnameFrame.setVisible(true);
        incorrectnameFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamelostLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamelostLabel1.setText("<html>You need to enter a valid <br/> name inorder to play!<html/>");
        incorrectnameFrame.getContentPane().add(gamelostLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 104));

        closegameButton3.setText("Close");
        closegameButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closegameButton3ActionPerformed(evt);
            }
        });
        incorrectnameFrame.getContentPane().add(closegameButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        startPage.add(incorrectnameFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 100));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/millionairegame/background.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        startPage.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, -1, -1));

        getContentPane().add(startPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNGActionPerformed
        if (evt.getSource() == ButtonNG) {
            rulesPage.setVisible(true);
            ButtonNG.setVisible(false);
            sidePanel.setVisible(true);
            if (nametextfield.getText() == null) {
                incorrectnameFrame.setVisible(true);
            }
            else {
            playerName = nametextfield.getText();
            nameLabel.setText(playerName);
            }
        }
    }//GEN-LAST:event_ButtonNGActionPerformed

    private void ButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlayActionPerformed
        question = new QuestionPool();
        questionPage.setVisible(true);
        rulesPage.setVisible(false);
        nameLabel.setText(playerName);
        getQuestion();
        setAnswers();
        getCount();
    }//GEN-LAST:event_ButtonPlayActionPerformed

    private void answerListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerListener
        optionA.setEnabled(true);
        optionB.setEnabled(true);
        optionC.setEnabled(true);
        optionD.setEnabled(true);
        if (null != answer) {
            switch (answer) {
                case "a":
                    if (optionA.isSelected()) {
                        getQuestion();
                        setAnswers();
                        getCount();
                        plcount++;
                        prizeLadder();
                    } else {
                        if (plcount <= 5) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $5000!");
                        }
                        else if (plcount >= 5 && plcount <= 10) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $50,000!");
                        }
                        else if (plcount >= 10 && plcount <= 15) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You have won the game, you take home $1,000,000!");
                        }
                    }
                    break;
                case "b":
                    if (optionB.isSelected()) {
                        getQuestion();
                        setAnswers();
                        getCount();
                        plcount++;
                        prizeLadder();
                    } else
                    {
                        gamelostFrame.setVisible(true);
                        if (plcount >= 5 && plcount <= 10) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $5000!");
                        }
                        else if (plcount >= 10 && plcount <= 14) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $50,000!");
                        }
                        else if (plcount == 15) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You have won the game, you take home $1,000,000!");
                        }
                    }
                    break;
                case "c":
                    if (optionC.isSelected()) {
                        getQuestion();
                        setAnswers();
                        getCount();
                        plcount++;
                        prizeLadder();
                    } else 
                    {
                        gamelostFrame.setVisible(true);
                        if (plcount <= 5) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $5000!");
                        }
                        else if (plcount >= 5 && plcount <= 10) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $50,000!");
                        }
                        else if (plcount >= 10 && plcount <= 15) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You have won the game, you take home $1,000,000!");
                        }
                    }
                    break;
                case "d":
                    if (optionD.isSelected()) {
                        getQuestion();
                        setAnswers();
                        getCount();
                        plcount++;
                        prizeLadder();
                    } else {
                        gamelostFrame.setVisible(true);
                        if (plcount >= 5 && plcount <= 10) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $5000!");
                        }
                        else if (plcount >= 10 && plcount <= 14) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You answered wrong, but you still take home $50,000!");
                        }
                        else if (plcount >= 15) {
                        gamelostFrame.setVisible(true);
                        gamelostLabel.setText("You have won the game, you take home $1,000,000!");
                        }
                    }
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_answerListener

    private void pafButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pafButtonActionPerformed
        pafFrame.setVisible(true);
        pafButton.setEnabled(false);
        switch (question.answer()) {
            case "a":
                pafLabel.setText("You chose phone a friend! Your friend thinks the answer is : " + question.a());
                break;
            case "b":
                pafLabel.setText("You chose phone a friend! Your friend thinks the answer is : " + question.b());
                break;
            case "c":
                pafLabel.setText("You chose phone a friend! Your friend thinks the answer is : " + question.c());
                break;
            case "d":
                pafLabel.setText("You chose phone a friend! Your friend thinks the answer is : " + question.d());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_pafButtonActionPerformed

    private void optionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAActionPerformed
        confirmAnswer.setEnabled(true);
    }//GEN-LAST:event_optionAActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        confirmAnswer.setEnabled(true);
    }//GEN-LAST:event_optionBActionPerformed

    private void optionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCActionPerformed
        confirmAnswer.setEnabled(true);
    }//GEN-LAST:event_optionCActionPerformed

    private void optionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDActionPerformed
        confirmAnswer.setEnabled(true);
    }//GEN-LAST:event_optionDActionPerformed

    private void closegameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closegameButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closegameButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        pafFrame.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton1ActionPerformed
        fiftyfiftyFrame.setVisible(false);
    }//GEN-LAST:event_closeButton1ActionPerformed

    private void fiftyfiftyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyfiftyButtonActionPerformed
        fiftyfiftyFrame.setVisible(true);
        fiftyfiftyButton.setEnabled(false);
        switch (question.answer()) {
            case "a":
                fiftyfiftyLabel.setText("You chose 5050! Two incorrect answers will now be disabled.");
                optionB.setEnabled(false);
                optionD.setEnabled(false);
                break;
            case "b":
                fiftyfiftyLabel.setText("You chose 5050! Two incorrect answers will now be disabled.");
                optionA.setEnabled(false);
                optionC.setEnabled(false);
                break;
            case "c":
                fiftyfiftyLabel.setText("You chose 5050! Two incorrect answers will now be disabled.");
                optionA.setEnabled(false);
                optionD.setEnabled(false);
                break;
            case "d":
                fiftyfiftyLabel.setText("You chose 5050! Two incorrect answers will now be disabled.");
                optionA.setEnabled(false);
                optionB.setEnabled(false);
                break;
            default:
                optionA.setEnabled(true);
                optionB.setEnabled(true);
                optionC.setEnabled(true);
                optionD.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_fiftyfiftyButtonActionPerformed

    private void ataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataButtonActionPerformed
        ataFrame.setVisible(true);
        ataButton.setEnabled(false);
        Random ataR = new Random();
        ataA = ataR.nextInt(50) + 1;
        ataB = ataR.nextInt(50) + 1;
        ataC = ataR.nextInt(50) + 1;
        ataD = ataR.nextInt(50) + 1;
        ataT = ataA + ataB + ataC + ataD;

        ataA = (70 / ataT) * ataA;
        ataB = (70 / ataT) * ataB;
        ataC = (70 / ataT) * ataC;
        ataD = (70 / ataT) * ataD;

        NumberFormat formatter = new DecimalFormat("#.00");

        switch (answer) {
            case "a":
                ataA = ataA + 30;
                ataLabel.setText("A = " + formatter.format(ataA) + "%." + ", " + "B = " + formatter.format(ataB) + "%." + ", " + "C = " + formatter.format(ataC) + "%." + ", " + "D = " + formatter.format(ataD) + ", ");
                break;
            case "b":
                ataB = ataB + 30;
                ataLabel.setText("A = " + formatter.format(ataA) + "%." + ", " + "B = " + formatter.format(ataB) + "%." + ", " + "C = " + formatter.format(ataC) + "%." + ", " + "D = " + formatter.format(ataD) + "%.");
                break;
            case "c":
                ataC = ataC + 30;
                ataLabel.setText("A = " + formatter.format(ataA) + "%." + ", " + "B = " + formatter.format(ataB) + "%." + ", " + "C = " + formatter.format(ataC) + "%." + ", " + "D = " + formatter.format(ataD) + "%.");
                break;
            case "d":
                ataD = ataD + 30;
                ataLabel.setText("A = " + formatter.format(ataA) + "%." + "\n" + "B = " + formatter.format(ataB) + "%." + ", " + "C = " + formatter.format(ataC) + "%." + ", " + "D = " + formatter.format(ataD) + "%.");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_ataButtonActionPerformed

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        ataFrame.setVisible(false);
    }//GEN-LAST:event_closeButton2ActionPerformed

    private void nametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextfieldActionPerformed

    private void closegameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closegameButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closegameButton1ActionPerformed

    private void closegameButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closegameButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closegameButton2ActionPerformed

    private void closegameButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closegameButton3ActionPerformed
        incorrectnameFrame.setVisible(false);
    }//GEN-LAST:event_closegameButton3ActionPerformed

    private void prizeLadder() {
        switch (plcount) {
            case 1:
                $0.setBackground(new Color(51, 102, 255));
                $500.setBackground(Color.RED);
                break;
            case 2:
                $500.setBackground(new Color(51, 102, 255));
                $1000.setBackground(Color.RED);
                break;
            case 3:
                $1000.setBackground(new Color(51, 102, 255));
                $2000.setBackground(Color.RED);
                break;
            case 4:
                $2000.setBackground(new Color(51, 102, 255));
                $3000.setBackground(Color.RED);
                break;
            case 5:
                $3000.setBackground(new Color(51, 102, 255));
                $5000.setBackground(Color.RED);
                break;
            case 6:
                $5000.setBackground(new Color(51, 102, 255));
                $7500.setBackground(Color.RED);
                break;
            case 7:
                $7500.setBackground(new Color(51, 102, 255));
                $10000.setBackground(Color.RED);
                break;
            case 8:
                $10000.setBackground(new Color(51, 102, 255));
                $15000.setBackground(Color.RED);
                break;
            case 9:
                $15000.setBackground(new Color(51, 102, 255));
                $25000.setBackground(Color.RED);
                break;
            case 10:
                $25000.setBackground(new Color(51, 102, 255));
                $50000.setBackground(Color.RED);
                break;
            case 11:
                $50000.setBackground(new Color(51, 102, 255));
                $75000.setBackground(Color.RED);
                break;
            case 12:
                $75000.setBackground(new Color(51, 102, 255));
                $250000.setBackground(Color.RED);
                break;
            case 13:
                $250000.setBackground(new Color(51, 102, 255));
                $500000.setBackground(Color.RED);
                break;
            case 14:
                $500000.setBackground(new Color(51, 102, 255));
                $1000000.setBackground(Color.RED);
                break;
            case 15:
                optionA.setEnabled(false);
                optionB.setEnabled(false);
                optionC.setEnabled(false);
                optionD.setEnabled(false);
                gamewonFrame.setVisible(true);
            default:
                break;
        }
    }

    private void setAnswers() {
        optionA.setText(question.a());
        optionB.setText(question.b());
        optionC.setText(question.c());
        optionD.setText(question.d());
    }

    private void getQuestion() {
        question.getQuestion();
        insertquestion.setText(question.question());
    }

    private void getCount() {
        Question.setText("Question : " + question.count().toString());
    }

    private QuestionPool question;
    private double ataA, ataB, ataC, ataD, ataT;
    private int plcount;
    String playerName;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel $0;
    private javax.swing.JPanel $1000;
    private javax.swing.JPanel $10000;
    private javax.swing.JPanel $1000000;
    private javax.swing.JPanel $15000;
    private javax.swing.JPanel $2000;
    private javax.swing.JPanel $25000;
    private javax.swing.JPanel $250000;
    private javax.swing.JPanel $3000;
    private javax.swing.JPanel $500;
    private javax.swing.JPanel $5000;
    private javax.swing.JPanel $50000;
    private javax.swing.JPanel $500000;
    private javax.swing.JPanel $7500;
    private javax.swing.JPanel $75000;
    private javax.swing.JButton ButtonNG;
    private javax.swing.JButton ButtonPlay;
    private javax.swing.JLabel Question;
    private javax.swing.JToggleButton ataButton;
    private javax.swing.JInternalFrame ataFrame;
    private javax.swing.JLabel ataLabel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton closegameButton;
    private javax.swing.JButton closegameButton1;
    private javax.swing.JButton closegameButton2;
    private javax.swing.JButton closegameButton3;
    private javax.swing.JButton confirmAnswer;
    private javax.swing.JToggleButton fiftyfiftyButton;
    private javax.swing.JInternalFrame fiftyfiftyFrame;
    private javax.swing.JLabel fiftyfiftyLabel;
    private javax.swing.JInternalFrame gamelostFrame;
    private javax.swing.JLabel gamelostLabel;
    private javax.swing.JLabel gamelostLabel1;
    private javax.swing.JInternalFrame gamewonFrame;
    private javax.swing.JLabel gamewonLabel;
    private javax.swing.JInternalFrame incorrectnameFrame;
    private javax.swing.JLabel insertquestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nameButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nametextfield;
    private javax.swing.JToggleButton optionA;
    private javax.swing.JToggleButton optionB;
    private javax.swing.JToggleButton optionC;
    private javax.swing.JToggleButton optionD;
    private javax.swing.JToggleButton pafButton;
    private javax.swing.JInternalFrame pafFrame;
    private javax.swing.JLabel pafLabel;
    private javax.swing.JPanel questionPage;
    private javax.swing.JPanel rulesPage;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel startPage;
    // End of variables declaration//GEN-END:variables
}
